# Generated by Django 3.2.7 on 2021-10-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="date",
            field=models.DateField(db_index=True),
        ),
    ]
