# Generated by Django 3.2.7 on 2021-12-27 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0003_workershiftcomment"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerShiftAggregateCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isoyearweek", models.PositiveSmallIntegerField(db_index=True)),
                ("yearmonth", models.PositiveSmallIntegerField(db_index=True)),
                ("count", models.IntegerField()),
                (
                    "worker",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="shifts.worker",
                    ),
                ),
            ],
        ),
    ]
