# Generated by Django 3.2.7 on 2022-02-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shifts", "0004_workershiftaggregatecount"),
    ]

    operations = [
        migrations.AddField(
            model_name="worker",
            name="email",
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
